export const NEXT_PUBLIC_CLOUDINARY_URL = process.env.NEXT_PUBLIC_CLOUDINARY_URL ;
export const NEXT_PUBLIC_BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL ;
export const NEXT_PUBLIC_FRONTEND_URL = process.env.NEXT_PUBLIC_FRONTEND_URL ;
export const NEXT_PUBLIC_GOOGLE_CLIENT_ID = process.env.EXT_PUBLIC_GOOGLE_CLIENT_ID ;
